name: job3_v4
on:
  push:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "hello job2" > test.txt
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: cat test.txt
