name: job_exo_2
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
    - run: echo "*****************************************************************"
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "-------------------------------------------------"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()
    steps:
    - run: echo "quelque chose s'est mal passé"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    if: always()
    steps:
    - run: echo "je m'execute qoui qu'il arrive"
