name: "Job - Exercice 2"
on:
  push:
  pull_request:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Bonjour"
  job2:
    needs: job1
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - run: echo "Comment"
  job3:
    runs-on: ubuntu-latest
    steps:
    - run: echo "allez"
  job4:
    runs-on: ubuntu-latest
    steps:
    - run: echo "vous ?"
