name: "job exo 2"
jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
    - run: echo "*****************************************************************"
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
      dayOfWeek=4
      if ($dayOfWeek > 5)
      then
        exit 1
      if
   job2:
     runs-on: ubuntu-latest
     needs: job1
     if: failure()
     steps:
     - run: echo "quelque chose s'est mal passé"
   job3:
     runs-on: ubuntu-latest
     needs: job2
     if: always()
     steps:
     - run: echo "je m'execute qoui qu'il arrive"
