name: "Job - Exercice 2"
on:
  workflow_dispatch:
jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: |
        echo "{date}={$(date +'%u')}"
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: if ($(date +'%u') > 5)
           then
             exit 1
           else
             echo "Bonjour"
           fi
  job2:
    needs: job1
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - run: echo "Comment"
  job3:
    runs-on: ubuntu-latest
    steps:
    - run: echo "allez"
  job4:
    runs-on: ubuntu-latest
    steps:
    - run: echo "vous ?"
