name: "Job - Exercice 2"
on:
  workflow_dispatch:
    inputs:
      day0fWeek:
        description: 'param1'
        required: true
        default: $(date +%u)
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: if ($day0fWeek > 5)
           then
             exit 1
           else
             echo "Bonjour"
           fi
  job2:
    needs: job1
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - run: echo "Comment"
  job3:
    runs-on: ubuntu-latest
    steps:
    - run: echo "allez"
  job4:
    runs-on: ubuntu-latest
    steps:
    - run: echo "vous ?"
