name: job_exo_2
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      dayOfWeek:
        description: 'Jour de la semaine'
        required: true
        default: $(date +%u)
jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
    - run: echo "*****************************************************************"
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
      if ($dayOfWeek > 5)
      then
        exit 1
      fi
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()
    steps:
    - run: echo "quelque chose s'est mal passé"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    if: always()
    steps:
    - run: echo "je m'execute qoui qu'il arrive"
