name: workflow_1
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispach:
jobs:
  build:
    runs-on: ubuntu-latest
steps:
- uses: actions/setup-node@v3
- name: Use Node.js
- run: npm install
- run: gulp build
- uses: actions/upload-artifact@v3
  with:
  name: Package_1_1
  path: dest
